name: Keep caches fresh
on:
    schedule:
        - cron: "5 4 1/4 * *" # alle 4 Tage

permissions:
    contents: read

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: 📥 Checkout Repository
              uses: actions/checkout@v4

            - name: ⏱ Cache notebook states
              uses: actions/cache@v3
              with:
                path: _cache
                key: ${{ runner.os }}-pluto_state_cache-v3-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}-${{ github.run_id }}
                restore-keys: |
                    ${{ runner.os }}-pluto_state_cache-v3-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}
              continue-on-error: true

            - name: ⏱ Cache .julia
              uses: actions/cache@v3
              with:
                path: ~/.julia
                key: ${{ runner.os }}-dotjulia-v1-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}-${{ github.run_id }}
                restore-keys: |
                    ${{ runner.os }}-dotjulia-v1-${{ hashFiles('**/Project.toml', '**/Manifest.toml') }}
              continue-on-error: true